analyzer_rules:
- unused_declaration
- unused_import

disabled_rules:
- discouraged_optional_collection
- explicit_acl
- explicit_top_level_acl
- explicit_type_interface
- explicit_enum_raw_value
- file_types_order
- force_cast
- force_unwrapping
- multiline_arguments_brackets
- no_extension_access_modifier
- no_grouping_extension
- trailing_whitespace
- trailing_closure
- unowned_variable_capture
- vertical_whitespace_between_cases

opt_in_rules:
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- convenience_type
- contains_over_range_nil_comparison
- discouraged_none_name
- discouraged_object_literal
- discouraged_optional_boolean
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- explicit_init
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
- file_name
- first_where
- function_default_parameter_at_end
- flatmap_over_map_reduce
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- large_tuple
- last_where
- legacy_multiple
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- nimble_operator
- nslocalizedstring_key
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefer_self_type_over_type_of_self
- private_action
- private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strong_iboutlet
- test_case_accessibility
- toggle_bool
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- xct_specific_matcher
- yoda_condition

included:
  - ServingSystem/Interface/ViewController
  - ServingSystem/Simulator

excluded:
  - Pods

attributes:
  always_on_same_line: ["@discardableResult", "@objc", "@IBAction", "@IBDesignable"]

line_length: 
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true

nesting:
  type_level: 2

type_body_length: 500 

file_length: 700

function_parameter_count: 6

warning_threshold: 1000

file_name:
  suffix_pattern: "Extensions?|\\+.*"

cyclomatic_complexity: 
  ignores_case_statements: true

conditional_returns_on_newline:
  if_only: true 

identifier_name:
  excluded:
    - id
    - x
    - y
  allowed_symbols: [_]
